/*
 * Copyright 2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package de.db.moredux

/**
 * A class to setup some MoRedux behavious
 */
object MoReduxSettings {
    enum class LogMode {
        FULL,
        MINIMAL,
        DISABLED
    }

    /**
     * Defines the amount of logs, generated by MoRedux
     * - FULL: Allow all logs
     * - MINIMAL: Allow only logs, that aim for MINIMAL logging, e.g. the dispatch of an action
     * - DISABLED: No logs at all
     */
    var logMode: LogMode = LogMode.MINIMAL

    /**
     * Set a callback method that is used for logging of debug messages. Use this to redirect MoRedux logging to your preferred
     * logging framework
     *
     * The callback function takes two parameters.
     * 1. String parameter: the log tag of the current log message
     * 2. String parameter: the log message itself
     */
    var logDebug: ((String?, String) -> Unit)? = null

    /**
     * Set a callback method that is used for logging of warning messages.
     *
     * For further explanations see [logDebug]
     */
    var logWarn: ((String?, String) -> Unit)? = null
}